# Spark configuration
spark.app.name=Java Data Analyzer
spark.master=local[*]
spark.ui.enabled=false
spark.log.level=ERROR
spark.warehouse.dir=spark-warehouse

# Application paths
app.sample.data.path=src/main/resources/dados_vendas.csv
app.output.dir=src/main/resources/results
